config/routes.rb
Rails.application.routes.draw do
  root "session#new"
  resources :session, :homes

  resources :notifications,only: [:index,:create]
  resources :users do
  member  do
    get 'show_user'  
    end
 end

  resources :posts do
    member  do
      get 'total_likes'
    end
    resources :comments
  end

  delete "delete_notification", to: "notifications#delete_notification"

  post "like", to: "likes#create"
  delete "unlike", to: "likes#destroy"
 
  post "follow", to: "follows#create"
  delete "unfollow", to: "follows#destroy"

  # get "follow_users", to: "users#follow_users"
  # get "following", to: "users#following"
  
  get "user_follow_users", to: "follows#user_follow_users"
  get "user_following_users", to: "follows#user_following_users"
  get "user_posts", to: "posts#user_posts"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post,counter_cache: true
  belongs_to :user
  has_many :notifications, as: :notifiable,dependent: :destroy
  before_validation :normalize_body, on: :create

  # attr_accessor :current_user

  def normalize_body
    self.body = body.capitalize
  end

  after_create_commit :notify_post_owner
   def notify_post_owner
    NotificationCreator.new(self, self.post.user, user).call
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post, only: [:index, :create, :edit, :update, :destroy]
  def index
    @comments = @post.comments.includes(:post)
  end

  def create
    @comment = @post.comments.build(comment_params)

    if @comment.save
      redirect_to post_comments_path(@post)
    end
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  def update
    @comment = @post.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to post_comments_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_comments_path(@post), status: :see_other
  end

  def set_post
      @post = Post.find(params[:post_id])
    end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :body)
    end    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="p-2 border rounded shadow bg-white text-center" style="min-width: 300px;">
      <% @comments.each do |comment|%>
  <p>
    <strong>Commenter:</strong>
  <%= comment.user.name%>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
  <p>
    <% if comment.user_id ==  @current_user.id%>

    <span class="list-inline-item"><%= link_to "Edit" , edit_post_comment_path(@post,comment.id),class: "btn btn-sm btn-secondary inline"%></span>
    <%= link_to "Delete", [comment.post, comment],class:"btn btn-sm btn-danger", data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
            } %>
  <% end %>
  </p>
  <% end %>
</div>

app/views/comments/_edit_comment_form.html.erb
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h3 class="text-dark mb-4 text-center">Comment form</h3>
    <%= form_with  model: [@post, @comment], local: true do |form| %>

    <%= form.hidden_field :commenter, value:@current_user.id  %>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit "Submit",class:'btn btn-sm btn-secondary' %>
    </p>
  <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h3 class="text-dark mb-4 text-center">Comment form</h3>
    <%= form_with model: [ @post, @post.comments.build ] do |form| %>

    <%= form.hidden_field :commenter, value:@current_user.id  %>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
      <%= link_to "back", post_path(@post),class:'btn btn-sm btn-secondary'%>
    </p>
  <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<%= render "edit_comment_form" , comment: @comment%>

app/views/comments/index.html.erb
<%= render  "shared/post_nav"%>


<h3 class="text-dark mb-4 text-center">All Comments</h3>

<%= render 'comments/comment'  %>
<%= render 'comments/form' %>