config/routes.rb
Rails.application.routes.draw do
  root "session#new"
  resources :session, :homes

  resources :notifications,only: [:index,:create]
  resources :users do
  member  do
    get 'show_user'  
    end
 end

  resources :posts do
    member  do
      get 'total_likes'
    end
    resources :comments
  end

  delete "delete_notification", to: "notifications#delete_notification"

  post "like", to: "likes#create"
  delete "unlike", to: "likes#destroy"
 
  post "follow", to: "follows#create"
  delete "unfollow", to: "follows#destroy"

  # get "follow_users", to: "users#follow_users"
  # get "following", to: "users#following"
  
  get "user_follow_users", to: "follows#user_follow_users"
  get "user_following_users", to: "follows#user_following_users"
  get "user_posts", to: "posts#user_posts"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recepient, class_name: "User", foreign_key: "recepient_id"
  belongs_to :actor, class_name: "User", foreign_key: "actor_id"
  belongs_to :notifiable, polymorphic: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	
	def index
    @notifications = current_user.notifications.includes(:actor, :notifiable)
    # @post = @current_user.posts.find_by(params[:post_id])
   
  end

  def delete_notification
    @notification = Notification.find(params[:id])
    @notification.destroy
    redirect_back fallback_location: notifications_path
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<%= render  "shared/post_nav"%>

<h3 style="text-align: center;">All Notifications</h3>

  <% @notifications.each do |notification|%>
      <div class="container d-flex justify-content-center mt-5">
      <div class="p-4 border rounded shadow bg-white" style="min-width: 450px;">
        <span><b><%= link_to notification.actor.name, user_path(notification.actor),class:"text-decoration-none text-dark"%></b></span>
        <span style="color:green;padding-left: 10%;"> 
          <% if notification.action == "started following you" %>
            <%=link_to  notification.action, user_path(notification.actor)%>
          <% elsif notification.action == "liked your post" %>
            <%=link_to  notification.action,  post_path(notification.notifiable.post)%>
          <% elsif notification.action == "commented on your post" %>
            <%=link_to  notification.action,  post_path(notification.notifiable.post)%>
          <% elsif notification.action == "created a new post" %>
            <%=link_to  notification.action,  post_path(notification.notifiable)%>
            <% else %>
            <p>No action</p>
          <% end %>
          </span>
        <span><%= link_to  "/delete_notification?id=#{notification.id}", data: {turbo_method: :delete, turbo_confirm:"are you sure you want to delete?"} do%>
        <i class="bi bi-x-square text-decoration-none text-dark" style="float:right;"></i>
        <% end %></span>
      </div>
    </div>   
<% end %>