config/routes.rb
Rails.application.routes.draw do
  root "session#new"
  resources :session, :homes

  resources :notifications,only: [:index,:create]
  resources :users do
  member  do
    get 'show_user'  
    end
 end

  resources :posts do
    member  do
      get 'total_likes'
    end
    resources :comments
  end

  delete "delete_notification", to: "notifications#delete_notification"

  post "like", to: "likes#create"
  delete "unlike", to: "likes#destroy"
 
  post "follow", to: "follows#create"
  delete "unfollow", to: "follows#destroy"

  # get "follow_users", to: "users#follow_users"
  # get "following", to: "users#following"
  
  get "user_follow_users", to: "follows#user_follow_users"
  get "user_following_users", to: "follows#user_following_users"
  get "user_posts", to: "posts#user_posts"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :notifications,foreign_key: :recepient_id, class_name: "Notification", dependent: :destroy
  

  has_many :followers, foreign_key: :following_id, class_name: "Follow", dependent: :destroy
  has_many :follower_users, through: :followers, source: :follower

  has_many :followings, foreign_key: :user_id, class_name: "Follow" , dependent: :destroy
  has_many :following_users, through: :followings, source: :followings

  
	validates :name,:email,:password,:phone, presence: true
  validates :bio,length: { minimum: 10 }

 	before_validation :normalize_name, on: :create
  after_validation :normalize_email

  validates :password, confirmation: true

 	validate :password_complexity
  validates :email,uniqueness: { case_sensitive: false }

 	validates :email,
      uniqueness: { message: "has already been taken" },
      format: { with: /\A[\w\.-]+@[\w\.-]+\.[a-zA-Z]{2,}\z/, message: "is not a valid email address" }

  validates :phone,uniqueness: true, format: { with: /\A(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[6789]\d{9}\z/,
                      message: "is not a valid Indian mobile number" }
  
  def password_complexity
    if password.present? && !password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{5,}$/)
      errors.add :password, "must include at least one lowercase letter, one uppercase letter, one digit, and be a minimum of 5 characters."
    end
  end

  private
    def normalize_name
      self.name = name.capitalize
    end

    def normalize_email
      self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  skip_before_action :auhenticate_user, only: [:create, :new]

  def index
    @users = User.all
  end

  def show
    # @user=User.find_by(id: session[:user_id])
     @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.valid?
      session[:user_id] = @user.id
      redirect_to new_session_path, success: "Your Account was Created Successfully! you can login now"
    else
      flash[:error] = @user.errors.full_messages
        redirect_to new_user_path
    end
  end 

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end
  
  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :bio, :phone, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_button.html.erb
<div class="user-action m-3" data-user-id="<%= user.id %>">
  <% if user.follower_users.exists?(@current_user.id) %>
    <%= link_to "/unfollow?following_id=#{user.id}", data: { turbo: false, turbo_method: :delete }, class: "unfollow-btn btn btn-sm btn-danger" do %>
      Unfollow
    <% end %>
  <% else %>
    <%= link_to "/follow?following_id=#{user.id}", data: { turbo: false, turbo_method: :post }, class: "follow-btn btn btn-sm btn-secondary" do %>
      Follow
    <% end %>
  <% end %>
</div>

app/views/users/_form.html.erb
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center">Edit Registration form</h2>

    <%= form_with model: @user  do |form|%>

      <div class="mb-3 text-center">
        <% if user.image.attached?%>
        <%= image_tag user.image ,size:'120x100', class: "rounded-circle w-25"%>
        <% end %>
        <%= form.file_field :image %>
      </div>

      <div class='mb-3'>
        <%= form.label :name%>
        <%= form.text_field :name, class:'form-control'%>
      </div>

      <div class='mb-3'>
        <%= form.label :email%>
        <%= form.email_field :email, class:'form-control'%>
      </div>

      <div class='mb-3'>
        <%= form.label :password%>
        <%= form.password_field :password, class:'form-control'%>
      </div>

      <div class='mb-3'>
        <%= form.label :password_confirmation%>
        <%= form.password_field :password_confirmation, class:'form-control'%>
      </div>

      <div class='mb-3'>
        <%= form.label :bio%>
        <%= form.text_field :bio, class:'form-control'%>
      </div>

      <div class='mb-3'>
        <%= form.label :phone%>
        <%= form.text_field :phone, class:'form-control'%>
      </div>

      <div class="mb-3">
        
      </div>

      <div class='mb-3 text-center'>
        <%= form.submit "submit", class:'btn btn-secondary'%>
      </div>
    <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<%= render "form" , user: @user%>

app/views/users/following.html.erb
<%= render  "shared/post_nav"%>
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
		<h2>All followings</h2>
		<ul>
		<% @followings.each do |follow|%>
		
		<li><%=link_to follow.following.name,show_user_user_path(follow.following_id),class:"text-decoration-none text-dark"%></li>
		<% end %>
		</ul>
	</div>
</div>

app/views/users/index.html.erb
<%= render  "shared/login_nav"%>
<h2>All Users</h2>
<ul>
<% @users.each do |user|%>
	<li><%= link_to  user.name, user_path(user)%></li>
	
<% end %>
</ul>

app/views/users/new.html.erb
<%= render  "shared/login_nav"%>
<%= render "layouts/flash" %>
<div class="container d-flex justify-content-center mt-5">
	<div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center">Registration form</h2>

		<%= form_with model: @user do |form|%>
			<div class='mb-3'>
				<%= form.label :name%><sup style="font-size: 15px;">*</sup>
				<%= form.text_field :name, class:'form-control'%>
			</div>

			<div class='mb-3'>
				<%= form.label :email%><sup style="font-size: 15px;">*</sup>
				<%= form.email_field :email, class:'form-control'%>
			</div>

			<div class='mb-3'>
				<%= form.label :password%><sup style="font-size: 15px;">*</sup>
				<%= form.password_field :password, class:'form-control'%>
			</div>

			<div class='mb-3'>
				<%= form.label :password_confirmation%><sup style="font-size: 15px;">*</sup>
				<%= form.password_field :password_confirmation, class:'form-control'%>
			</div>

			<div class='mb-3'>
				<%= form.label :bio%>
				<%= form.text_field :bio, class:'form-control'%>
			</div>

			<div class='mb-3'>
				<%= form.label :phone%><sup style="font-size: 15px;">*</sup>
				<%= form.text_field :phone, class:'form-control'%>
			</div>

			<div class="mb-3">
				<%= form.label :image %>
    		<%= form.file_field :image %>
			</div>

			<div class='mb-3 text-center'>
				<%= form.submit "submit", class:'btn btn-secondary'%>
			</div>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<%= render  "shared/post_nav"%>
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center"><%= @user.name%> </h2>
    <%= form_with  do |form|%>
      <div class="mb-3 text-center">
        <% if @user.image.attached?%>
        <%= image_tag @user.image ,size:'120x100', class: "rounded-circle w-25"%>
        <% end %>
      </div>
      <div class="mb-3 list-inline text-center">
        <span class="list-inline-item">
          <%= link_to "posts :", user_posts_path(user_id: @user.id), class:"text-decoration-none text-dark"%>
          <%= @user.posts_count%>
        </span>
        <span class="list-inline-item">
          <%= link_to "Followers :", user_follow_users_path(following_id: @user.id), class:"text-decoration-none text-dark"%>
          <%= @user.followers.count%>
        </span>
        <span class="list-inline-item">
          <%= link_to "Following :", user_following_users_path(user_id: @user.id), class:"text-decoration-none text-dark"%> 
          <%= @user.followings.count%>
        </span>
      </div>
      <div class="mb-3 text-center">
        <%= form.label "email:"%>
        <%= @user.email %>
      </div>
      <div class="mb-3 text-center">
        <% if @user.bio.present?%>
          <%= form.label "bio:"%>
          <%= @user.bio%>
        <% else %>
        <% end %>
      </div>
      <div class="mb-3 text-center">
        <%= form.label "phone:"%>
        <%= @user.phone %>
      </div>
      <div class="mb-3 list-inline text-center">
        <% if @user.id == @current_user.id%>
          <span class="list-inline-item"><%= link_to "Edit" , edit_user_path(@user),class: "btn btn-secondary inline"%></span>
          <span class="list-inline-item "><%= link_to "Delete" , user_path(@user), data: { turbo_method: :delete,turbo_confirm: "Are you sure?"},class:'btn btn-secondary' %></span>
          <span class="list-inline-item"><%= link_to "Log out", session_path(@user), data:  { turbo_method: :delete,  turbo_confirm: "Are you sure?" },class: "btn btn-secondary inline" %>
          </span>
          <% end %>
      </div>
    <% end %>
  </div>
</div>