config/routes.rb
Rails.application.routes.draw do
  root "session#new"
  resources :session, :homes

  resources :notifications,only: [:index,:create]
  resources :users do
  member  do
    get 'show_user'  
    end
 end

  resources :posts do
    member  do
      get 'total_likes'
    end
    resources :comments
  end

  delete "delete_notification", to: "notifications#delete_notification"

  post "like", to: "likes#create"
  delete "unlike", to: "likes#destroy"
 
  post "follow", to: "follows#create"
  delete "unfollow", to: "follows#destroy"

  # get "follow_users", to: "users#follow_users"
  # get "following", to: "users#following"
  
  get "user_follow_users", to: "follows#user_follow_users"
  get "user_following_users", to: "follows#user_following_users"
  get "user_posts", to: "posts#user_posts"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user,counter_cache: true
  has_many_attached :images
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :notifications, as: :notifiable,dependent: :destroy
  accepts_nested_attributes_for :comments, :likes
  validates :title, :body, presence: true
  before_validation :normalize_title, on: :create
  validates :body,length: { minimum: 10 }
  after_create_commit :notify_post_owner

  def already_liked?(c_user)
    likes.exists?(user_id: c_user.id)
  end
  
  def notify_post_owner
    self.user.follower_users.each do |follower|
      NotificationCreator.new(self, follower, self.user).call
    end
  end
  private
    def normalize_title
      self.title = title.capitalize
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_post, only: [:show, :like, :unlike]
  def index
    @posts = @current_user.posts.paginate(page: params[:page], per_page: 2)
  end

  def show
    @post = Post.find(params[:id])
  end

  def user_posts
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:user)
  end

  def like
    current_user.likes.create(post: @post)
    redirect_back fallback_location: posts_path
  end

  def unlike
    like = current_user.likes.find_by(post: @post)
    like&.destroy
    redirect_back fallback_location: posts_path
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render :new
    end
  end

  def total_likes
    @post = Post.find(params[:id])
    @likes = Like.includes(:user).where(post_id: @post.id)
  end

  def edit 
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :user_id, images: [])
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= render  "shared/post_nav"%>
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center">Edit Post</h2>

    <%= form_with model: @post do |form|%>

      <div class="mb-3">
        <%= form.hidden_field :user_id, value:@current_user.id  %>
      </div>

      <div class='mb-3'>
        <%= form.label :title%>
        <%= form.text_field :title, class:'form-control'%>
      </div>

      <div class='mb-3'>
        <%= form.label :body%>
        <%= form.text_field :body, class:'form-control'%>
      </div>

      <div class='mb-3 text-center'>
        <%= form.submit "submit", class:'btn btn-secondary'%>
      </div>
    <% end %>
    </div>
</div>

app/views/posts/_like_button.html.erb
<% if post.already_liked?(@current_user) %>
  <%= link_to  "/unlike?post_id=#{post.id}", data: { turbo: false, turbo_method: :delete}, class:"unlike-btn" do %>
   <i class="bi bi-hand-thumbs-down text-decoration-none text-dark"></i>
  <% end %>
  
<% else %>
  <%= link_to  "/like?post_id=#{post.id}", data: { turbo: false, turbo_method: :post},class:"like-btn" do %>
    <i class="bi bi-hand-thumbs-up text-decoration-none text-dark"></i>
  <% end %>
<% end %>

app/views/posts/_post_action.html.erb
<div class="post-action mt-2">

  <%= render "posts/like_button", post: post %>

  <%= link_to post_comments_path(post) ,data: { turbo_method: :get} do %>
    <i class="bi bi-chat text-decoration-none text-dark" style="padding-left: 58px;"></i>
  <% end %>
  <div class="post-action mt-0">
    <span style="font-size: 15px;">
      <%= link_to "Likes:", total_likes_post_path(post), class:"text-decoration-none text-dark"%>
      <%= post.likes_count %></span>
    <span  style="font-size: 15px;">Comments:<%= post.comments_count %></span>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render "form" , post: @post%>

app/views/posts/index.html.erb
<%= render  "shared/post_nav"%>

 <% if @posts.present?%> 
<div class='posts-container d-flex flex-column mt-3 p-3 container-sm align-items-center' style="gap: 30px">
  <% @posts.each do |post|%>
    <div class="post-container d-flex flex-column p-3 border rounded shadow-sm w-100" style="gap: 15px; max-width: 590px;">
      <div class="user-detail d-flex align-items-center border rounded shadow-sm w-100" style="gap: 10px">      
        <div class="user-image m-2">
          <%= image_tag post.user.image.variant(resize_to_limit: [200,200]), class: 'rounded-circle', width: '60', height: '60' %>   
        </div>
        <div class="user-name fw-semibold">
          <%= post.user.name %>   
        </div>
      </div>  
      <div class="post-detail"></div>
      <div class="post-title fs-4 fw-semibold">
                <%= link_to  post.title, post_path(post),class: 'text-decoration-none text-dark'%>
        </div>
        <div class="post-images d-flex" style="gap: 5px">
          <% post.images.each do |image| %>
            <div class="post-image">
              <%= image_tag image.variant(resize_to_limit: [300,300]),size:"135x135" %>
            </div>
          <% end %>
        </div>
    </div>
  <% end %>
</div>
 <% else %> 
<div class="post-container d-flex flex-column p-3 border rounded shadow-sm w-100 align-items-center">

 <p>No post here</p>
 
</div>

<% end %> 
<%= will_paginate @posts%>

app/views/posts/new.html.erb
<%= render  "shared/post_nav"%>
<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2 class="text-dark mb-4 text-center">Create Post</h2>

    <%= form_with model: @post do |form|%>

      <div class="mb-3">
             <%= form.hidden_field :user_id, value:@current_user.id  %>
          </div>

      <div class='mb-3'>
        <%= form.label :title%>
        <%= form.text_field :title, class:'form-control'%>
      </div>

      <div class='mb-3'>
        <%= form.label :body%>
        <%= form.text_field :body, class:'form-control'%>
      </div>

      <div class="mb-3">
        <%= form.label :images %>
        <%= form.file_field :images, multiple: true %>
      </div>

      <div class='mb-3 text-center'>
        <%= form.submit "submit", class:'btn btn-secondary'%>
      </div>
    <% end %>
    </div>
</div>

app/views/posts/show.html.erb
<%= render  "shared/post_nav"%>

<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 500px;">
    <h2 class="text-dark mb-4 text-center"><%= @post.user.name%> </h2>
      <%= form_with  do |form|%>

        <div class="mb-3 text-center">
          <%= form.label "title:"%>
          <%= @post.title %>
        </div>

        <div class="mb-3 text-center">
          <%= form.label "body:"%>
          <%= @post.body%>
        </div>

        <div class="mb-3 text-center">
          <% if @post.images.attached?%>
          <% @post.images.each do |image|%>
          <%= image_tag  image.variant(resize_to_limit: [300,300]),size:'150x150'%>
          <% end %>
          <% else %>
          <p>No images found</p>
          <% end %>
        </div>
          <%= render "posts/post_action", post: @post%>
        
        <% if @post.user.id == @current_user.id%>
        
        <ul class="list-inline text-center">
          <li class="list-inline-item"><%= link_to "Edit" , edit_post_path(@post),class: "btn btn-secondary inline"%></li>
          <li class="list-inline-item "><%= link_to "Delete" , post_path(@post), data: { turbo_method: :delete,turbo_confirm: "Are you sure?"},class:'btn btn-secondary' %></li>
        </ul>
      <% end %>


      <% end %>
  </div>
</div>

app/views/posts/total_likes.html.erb
<%= render  "shared/post_nav"%>

<div class="container d-flex justify-content-center mt-5">
  <div class="p-4 border rounded shadow bg-white" style="min-width: 400px;">
    <h2>All Likes</h2>
    <ul>
     <% @likes.each do |like|  %>
     
     <li> <%= link_to like.user.name, user_path(like.user_id),class:"text-decoration-none text-dark"%></li>
    <% end %>
    </ul>
</div>
</div>

app/views/posts/user_posts.html.erb
<%= render  "shared/post_nav"%>

 <% if @posts.present?%> 
<div class='posts-container d-flex flex-column mt-3 p-3 container-sm align-items-center' style="gap: 30px">
  <% @posts.each do |post|%>
    <div class="post-container d-flex flex-column p-3 border rounded shadow-sm w-100" style="gap: 15px; max-width: 590px;">
      <div class="user-detail d-flex align-items-center border rounded shadow-sm w-100" style="gap: 10px">      
        <div class="user-image m-2">
          <%= image_tag post.user.image.variant(resize_to_limit: [200,200]), class: 'rounded-circle', width: '60', height: '60' %>   
        </div>
        <div class="user-name fw-semibold">
          <%= post.user.name %>   
        </div>
      </div>  
      <div class="post-detail"></div>
      <div class="post-title fs-4 fw-semibold">
          <%= link_to  post.title, post_path(post),class: 'text-decoration-none text-dark'%>
      </div>
        <div class="post-images d-flex" style="gap: 5px">
          <% post.images.each do |image| %>
            <div class="post-image">
              <%= image_tag image.variant(resize_to_limit: [300,300]),size:"135x135" %>
            </div>
          <% end %>
        </div>
    </div>
  <% end %>
</div>
 <% else %> 
<div class="post-container d-flex flex-column p-3 border rounded shadow-sm w-100 align-items-center">

 <p>No post here</p>
 
</div>

<% end %> 